"""
    auto generated by django
"""

from django.apps import AppConfig


class QuizAppConfig(AppConfig):
    """provides some information about the app to settings.py"""
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'quiz_app'
