# Generated by Django 4.0.1 on 2022-01-21 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Date Created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 15, 52, 31, 726487, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
