# Generated by Django 4.0.1 on 2022-01-22 10:18

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_date created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Date Created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
    ]
