# Generated by Django 4.0.1 on 2022-11-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quiz_date last edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Time',
            new_name='time',
        ),
    ]
